### ISSUE TITLE
Incomplete Property label in HTML Embed Component

### ISSUE THREAD

**Issue by GoharAkram** [webstudio-is/webstudio-builder#2104]
![image](https://github.com/webstudio-is/webstudio-builder/assets/136603139/975c6ae6-d485-48fa-8004-0c0f0d5f4b69)

Last.. Execute Script on The Canvas

**Comment by kof** [comment]
@istarkov something is wrong with layout, there should be a plenty of space according to design

<img width="350" alt="Screenshot 2023-08-13 at 10 48 12" src="https://github.com/webstudio-is/webstudio-builder/assets/52824/37b8df49-3b5d-47de-bea5-5ad87544285e">

**Comment by istarkov** [comment]
<img width="240" alt="image" src="https://github.com/webstudio-is/webstudio-builder/assets/5077042/b460078f-e64e-4d7b-90dd-6aeb4b925223">

There can be a `-` sign, so layout made keeping that in mind.

**Comment by kof** [comment]
@taylornowotny seems like design doesn't have any examples of boolean prop with delete button

https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=6555-95012&mode=design&t=7SiAbZkPiLmk2Vnu-0

**Comment by kof** [comment]
Quick workaround: rename to. "Run Code on Canvas"

**Comment by taylornowotny** [comment]
@kof There is indeed a design with the remove button included. It's the first one in the list of property controls.
<img width="669" alt="Screenshot 2023-08-13 at 10 24 58 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/08d8af54-fb59-4f07-984c-480f262aa507">

And the reason the properties don't look right is becuase the design wasn't fully implemented, as I described in response to this issue. https://github.com/webstudio-is/webstudio-builder/issues/2047#issuecomment-1668260471

**Comment by taylornowotny** [comment]
Link to figma: https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=6107%3A55336&mode=design&t=stSI9yFXKECkLlJm-1

**Comment by kof** [comment]
<img width="542" alt="Screenshot 2023-08-13 at 19 51 09" src="https://github.com/webstudio-is/webstudio-builder/assets/52824/ab30494d-2425-44ab-813f-a9f29e0c6926">

@istarkov somehow both delete and switch fit with that text in figma

**Comment by taylornowotny** [comment]
It's really simple, as I described in my linked comment. There should be 8px min space between the label and the control and the label should not truncate until it reaches that limit, as described in the design docs. Currently it truncates way too early, leaving a large amount of space between the label and control.

**Comment by kof** [comment]
Found the reason, the left side is about 5 px short, I think we should be setting fixed width for the buttons on the right and let the left side grow, right now its the other way around, left side uses spacing-24 token which is 144px

<img width="607" alt="Screenshot 2023-08-13 at 20 00 54" src="https://github.com/webstudio-is/webstudio-builder/assets/52824/3ff38c1a-cf90-49aa-9fb1-104c9c6f42e1">

**Comment by taylornowotny** [comment]
Am I missing something? Why use a fixed size at all? Just give the flex container an 8px gap, set the label to grow, and that should be it. The large fixed size on the control is what's causing the problem.

**Comment by istarkov** [comment]
The issue with figma css that here is layout reused from other props. 

And it will not work with ordinary inputs because label would try to fit all the available space.
To be it compatible with everything label was made to have a fixed width. Width for label was selected from our theme so `-` button and switch would fit together.
Anyway would be good in for every layout to write what is fixed and what is not. 

And have in mind that any text can overflow - different language for example.

Developers are trying to reduce amount of code using same layouts etc everywhere.  
Im not big fan of this reusability, but that figma css for specific usecase is not how this is made internally ;-)

**Comment by taylornowotny** [comment]
Understood, but please understand that:

1. The design never uses fixed-width labels.
    - Controls are often a fixed width and labels should expand to fill the available space, with respect for the gap. This is the general pattern used across the whole design and I can't think of any exceptions atm. This should be the standard pattern.
    
2. The design almost always specifies when a fixed width is used. Simply select an element, look in the code, and if it has a specified width or height in the CSS then it is fixed. Otherwise it is not. If you have question about a specific design then it's easy to ask and I'm happy to clarify.

**Comment by TrySound** [comment]
The topic is fixed with shorter label

**Comment by kof** [comment]
Our sizing is still wrong, we have a fixed left side where text is, but instead it should be auto growing and fixed size should be on controls. Our left size should be also bigger by about 5px if you compare the design
